version: "3.4"

services:
  zeppelin:
    image: apache/zeppelin:0.8.2
    ports:
       - "8080:8080"
       - "4042:4040"
    volumes:
     - "~/projects/network/docker/volumes/zeppelin/conf:/zeppelin/conf"
     - "~/projects/network/docker/volumes/zeppelin/logs:/logs"
     - "~/projects/network/docker/volumes/zeppelin/notebook:/zeppelin/notebook"
     - "~/projects/network/docker/volumes/zeppelin/data:/data"
     - "~/projects/network/docker/volumes/spark/conf:/opt/spark-2.4.4-bin-hadoop2.7/conf"
     - "/opt/spark-2.4.4-bin-hadoop2.7:/opt/spark-2.4.4-bin-hadoop2.7"
     - "/opt/jars:/opt/jars"
    restart: unless-stopped
    
    
